#!/bin/bash

# Copyright (C) 2025 Murilo Gomes Julio
# SPDX-License-Identifier: GPL-2.0-only

# Mestre da Info
# Site: https://www.mestredainfo.com.br

while true; do
	echo ""
	echo "------------- MINJSInstall-------------"
	echo "Selecione uma opção:"
	echo "1. Instalar NVM"
	echo "2. Instalar Node"
	echo "3. Remover o NVM, NPM e Node"
	echo "4. Sair"
	echo "------------- /MINJSInstall-------------"
	echo ""
	
	read -p "Opções: " option
	
	case $option in
		1)
			read -p "Digite a versão do NVM: " versaodonvm
			#Baixa o NVM e instala
			wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v$versaodonvm/install.sh | bash

			#Exporta o comando nvm para ser usado
			export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
			[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
			;;
		2)
			#Instala o NPM e Node
			nvm install node
			;;
		3)
			#Remove o NVM, NPM e Node
			rm -rf $NVM_DIR ${HOME}/.npm ${HOME}/.bower && unset NVM_DIR
			;;
		4)
			echo "Saindo..."
			exit 0
			;;
		*)
			echo "Opção inválida. Por favor, escolha uma opção válida."
			;;
	esac
done
